# Generated by Django 3.1.7 on 2021-02-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_consume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consume',
            old_name='food_consmed',
            new_name='food_consumed',
        ),
    ]
